# Generated by Django 5.2.9 on 2025-12-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='max_stake',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='name',
            field=models.CharField(default='New Shop', max_length=255),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
