# Generated by Django 5.2.9 on 2025-12-26 12:37

import accounts.models
from django.db import migrations, models
from django.utils.text import slugify


def ensure_codes(apps, schema_editor):
    ShopUser = apps.get_model('accounts', 'ShopUser')
    for user in ShopUser.objects.all():
        if user.shop_code:
            continue
        base = slugify(user.name or user.username or 'shop') or 'shop'
        candidate = base
        suffix = 1
        while ShopUser.objects.filter(shop_code=candidate).exclude(pk=user.pk).exists():
            suffix += 1
            candidate = f"{base}-{suffix}"
        user.shop_code = candidate
        user.save(update_fields=['shop_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shopuser_commission_rate_shopuser_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='shop_code',
            field=models.SlugField(default=accounts.models.generate_default_shop_code, editable=False, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.RunPython(ensure_codes, migrations.RunPython.noop),
    ]
