# Generated by Django 5.2.9 on 2025-12-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shopuser_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='two_factor_method',
            field=models.CharField(choices=[('totp', 'Authenticator app')], default='totp', max_length=20),
        ),
    ]
