# Generated by Django 5.2.9 on 2026-02-21

import random
import string
import uuid

from django.db import migrations, models


def _unique_email(apps, candidate: str, exclude_pk: int):
    ShopUser = apps.get_model("accounts", "ShopUser")
    value = candidate.lower()
    while ShopUser.objects.filter(contact_email__iexact=value).exclude(pk=exclude_pk).exists():
        local, domain = value.split("@", 1)
        value = f"{local}-{uuid.uuid4().hex[:4]}@{domain}"
    return value


def _unique_phone(apps, candidate: str, exclude_pk: int):
    ShopUser = apps.get_model("accounts", "ShopUser")
    value = candidate
    while ShopUser.objects.filter(contact_phone=value).exclude(pk=exclude_pk).exists():
        value = f"9{''.join(random.choices(string.digits, k=9))}"
    return value


def _unique_human_shop_id(apps, exclude_pk: int):
    ShopUser = apps.get_model("accounts", "ShopUser")
    value = f"SHOP-{uuid.uuid4().hex[:6].upper()}"
    while ShopUser.objects.filter(human_shop_id=value).exclude(pk=exclude_pk).exists():
        value = f"SHOP-{uuid.uuid4().hex[:6].upper()}"
    return value


def forwards(apps, schema_editor):
    ShopUser = apps.get_model("accounts", "ShopUser")

    for user in ShopUser.objects.all().order_by("id"):
        email = (user.contact_email or "").strip().lower()
        phone = (user.contact_phone or "").strip()
        human_shop_id = (user.human_shop_id or "").strip()

        if not email:
            email = f"shop-{user.pk}@dummy.lulu-bingo.local"
        email = _unique_email(apps, email, user.pk)

        if not phone:
            phone = f"9{user.pk:09d}"[-10:]
            if not phone.startswith("9"):
                phone = f"9{phone[1:]}"
        phone = _unique_phone(apps, phone, user.pk)

        if not human_shop_id:
            human_shop_id = _unique_human_shop_id(apps, user.pk)

        updates = {}
        if user.contact_email != email:
            updates["contact_email"] = email
        if user.contact_phone != phone:
            updates["contact_phone"] = phone
        if user.human_shop_id != human_shop_id:
            updates["human_shop_id"] = human_shop_id

        if updates:
            ShopUser.objects.filter(pk=user.pk).update(**updates)


def backwards(apps, schema_editor):
    # Keep data as-is when rolling back.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_shopuser_totp_secret_shopuser_two_factor_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopuser",
            name="human_shop_id",
            field=models.CharField(blank=True, editable=False, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="shopuser",
            name="two_factor_email_code",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
        migrations.AddField(
            model_name="shopuser",
            name="two_factor_email_code_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="shopuser",
            name="contact_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="shopuser",
            name="contact_phone",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="shopuser",
            name="two_factor_method",
            field=models.CharField(
                choices=[("totp", "Authenticator app"), ("email_code", "Email code")],
                default="totp",
                max_length=20,
            ),
        ),
    ]
