# Generated by Django 5.2.9 on 2026-05-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_shopuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='bonus_contribution_per_cartella',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='bonus_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='bonus_funding_source',
            field=models.CharField(choices=[('players', 'Players'), ('shop', 'Shop')], default='players', max_length=20),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='bonus_max_rounds',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='bonus_min_rounds',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='bonus_next_award_round',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='bonus_pot_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='bonus_round_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
