# Generated by Django 5.2.9 on 2026-04-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_operation_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet_debit', 'Bet debit'), ('bet_credit', 'Bet credit'), ('lulu_cut_debit', 'Lulu cut debit'), ('adjustment', 'Adjustment')], max_length=30),
        ),
    ]
