# Generated by Django 5.2.9 on 2026-05-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_game_board_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('shop_fixed4', 'Shop Fixed 4'), ('shop_online', 'Shop Online'), ('shop_offline', 'Shop Offline')], default='standard', max_length=20),
        ),
    ]
