# Generated by Django 5.2.9 on 2026-05-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_alter_game_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bonus_awarded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='game',
            name='bonus_awarded_cartella_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='bonus_contribution_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
